name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - threads-v2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Celeste Loader
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.203"

      - name: Install mono
        run: sudo apt-get install mono-devel

      - name: Build Csproj
        run: |
          cd loader && dotnet workload restore && cd ..
          make publish

      - uses: actions/upload-artifact@v4
        with:
          name: webleste-loader
          path: frontend/dist/
          compression-level: 6

  upload:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all

    steps:
      - name: Delete old release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: latest
          github_token: ${{ github.token }}

      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: webleste-loader
          path: dist/

      - name: Compress artifact
        run: tar cavf webleste-loader.tar.zst -C dist .

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: Continuous Build
          tag: latest
          commit: threads-v2
          body: "${{ github.event.head_commit.url }} ${{ github.event.head_commit.message }}"
          artifacts: webleste-loader.tar.zst

  deployr58:
    name: Deploy to celeste.r58playz.dev
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: webleste-loader
          path: dist/

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=celeste-wasm-threads
